services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fintrack_db}
      POSTGRES_USER: ${POSTGRES_USER:-fintrack_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CHANGE_THIS_LOCAL_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fintrack_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fintrack-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB:-fintrack_db};Username=${POSTGRES_USER:-fintrack_user};Password=${POSTGRES_PASSWORD:-CHANGE_THIS_LOCAL_POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER:-FinTrack.Api}
      Jwt__Audience: ${JWT_AUDIENCE:-FinTrack.Client}
      Jwt__Secret: ${JWT_SECRET:-CHANGE_THIS_TO_A_LONG_SECURE_SECRET_KEY_WITH_AT_LEAST_32_CHARS}
      Jwt__ExpirationMinutes: ${JWT_EXPIRATION_MINUTES:-60}
      Database__ApplyMigrationsOnStartup: true
    ports:
      - "8080:8080"

volumes:
  fintrack_postgres_data:
